# Intelligent Resume Screening and Job Matching Analytics

This notebook provides analysis and insights into the resume screening system.

In [7]:
import os
os.getcwd()

'c:\\Users\\dell\\Desktop\\resume_project\\Intelligent-resume-checker-and-job-matching-analytics-system\\notebooks'

In [8]:
import pandas as pd

resumes = pd.read_csv("../data/raw/resume_dataset.csv")
jobs = pd.read_csv("../data/raw/job_description_dataset.csv")

resumes.head()

,resume_id,candidate_name,email,phone,location,education,experience_years,current_role,target_role,skills,certifications,expected_salary_lpa,resume_summary
0,1,Jerry Thomas,scannon@example.net,5815367803,Bangalore,M.Tech,9,Data Analyst,AI Engineer,"AWS, Python, Kubernetes, React, C++, Git, GCP,...",NaN,27,9 years experienced professional skilled in AW...
1,2,Mr. Zachary Miller DVM,spearsmiranda@example.net,(787)477-4212,Delhi,MBA,5,Backend Developer,Cloud Engineer,"Linux, Communication, Leadership, Power BI, Ja...",NaN,3,5 years experienced professional skilled in Li...
2,3,Leah Johnson,brandon52@example.net,535.685.0007x731,Delhi,M.Tech,5,Full Stack Developer,Full Stack Developer,"CSS, Power BI, MongoDB, Teamwork, C, GCP, Seab...",AWS Certified,13,5 years experienced professional skilled in CS...
3,4,Evan Flores,merrittwilliam@example.org,(308)377-9563x2228,Delhi,M.Sc,1,Frontend Developer,Frontend Developer,"Kubernetes, Machine Learning, GitHub, Python, ...",Google Data Engineer,30,1 years experienced professional skilled in Ku...
4,5,Tammy Freeman,james27@example.org,2154384207,Bangalore,M.Sc,7,Full Stack Developer,Frontend Developer,"Linux, MySQL, Communication, PostgreSQL, R, Gi...",AWS Certified,28,7 years experienced professional skilled in Li...

In [9]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

resumes['combined'] = (
    resumes['skills'].astype(str) + " " +
    resumes['experience_years'].astype(str) + " " +
    resumes['resume_summary'].astype(str)
)
resumes['clean_text'] = resumes['combined'].apply(clean_text)

jobs['clean_text'] = (jobs['required_skills'] + " " + jobs['job_description']).apply(clean_text)

In [11]:
!python -m pip install fastapi uvicorn pandas scikit-learn

Requirement already satisfied: fastapi in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (0.129.0)
Requirement already satisfied: uvicorn in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (0.40.0)
Requirement already satisfied: pandas in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.0)
Requirement already satisfied: scikit-learn in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.8.0)
Requirement already satisfied: starlette<1.0.0,>=0.40.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from fastapi) (0.52.1)
Requirement already satisfied: pydantic>=2.7.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from fastapi) (2.12.5)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from fastapi) (0.0.4)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from starlette<1.0.0,>=0.40.0->fastapi) (4.12.1)
Requirement already satisfied: idna>=2.8 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from anyio<5,>=3.6.2->starlette<1.0.0,>=0.40.0->fastapi) (3.11)
Requirement already satisfied: click>=7.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from uvicorn) (8.3.1)
Requirement already satisfied: h11>=0.8 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from uvicorn) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: colorama in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click>=7.0->uvicorn) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic>=2.7.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic>=2.7.0->fastapi) (2.41.5)
Requirement already satisfied: six>=1.5 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

resume_vec = vectorizer.fit_transform(resumes['clean_text'])
job_vec = vectorizer.transform(jobs['clean_text'])

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

scores = cosine_similarity(job_vec[0], resume_vec)[0]
resumes['match_score'] = scores * 100

resumes[['candidate_name', 'match_score']].sort_values(by='match_score', ascending=False).head(5)

         candidate_name  match_score
1594      Michelle King    73.275992
8530  Christopher Nolan    73.266198
2993    Alicia Sullivan    73.235941
9886    Kimberly Newton    70.874127
5660        Kelli Smith    69.454058

In [17]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [18]:
resumes.sort_values(by='match_score', ascending=False)\
       .head(10)\
       .to_csv("../data/processed/top_matches.csv", index=False)